### ISSUE TITLE
'the input device is not a TTY' when executing minke commands on macOS

### ISSUE THREAD

**Issue by cameroncooke** [nicholasjackson/minke#32]
On macOS 10.11 running Docker for Mac 1.12.1 and executing the the command as shown in Quick Start guide:

```
curl -Ls https://get.minke.rocks | bash -s ' -g minke-generator-go -o $(pwd) -n github.com/nicholasjackson -a myservice'
```

I get the response:

```
Running command:  -g minke-generator-go -o $(pwd) -n github.com/nicholasjackson -a myservice
f9dce9132255a8ad06e07475cf9b7cf72a3e87b085ba7830262bb44fac399053
the input device is not a TTY
minke_lyhtw8k2lxsmlx0ktomgrll5noeuhgnf
```

I've had the same error on iTerm and Terminal, and using the shells ZSH and Bash.  I don't think macOS supports TTYs.

Quick Google reveals that this might be an issue with Docker and suggestions are to remove the -i (interactive) option.

**Comment by algal** [comment]
I'm seeing the same thing on macOS 10.11 and Docker for 1.12.20-rc1-beta27 (build:12496).

**Comment by nicholasjackson** [comment]
I will take a look at this, it should attempt to detect if TTY is available before setting the option.  The problem with removing the interactive terminal mode is that you can no longer quit the session as it is not possible to send Ctrl-C to minke.

**Comment by nicholasjackson** [comment]
@cameroncooke @algal are you both using version 1.13.16?
